version: "3.3"
services:
  redis:
    image: redis:latest
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - ENV=develop
    
  # mongo_userdb:
  #   image: mongo:latest
  #   container_name: db_user
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: comp3122
  #     MONGO_INITDB_ROOT_PASSWORD: 23456
  #     MONGO_INITDB_DATABASE: admin
  #   volumes:
  #     - ./user-init.js:/docker-entrypoint-initdb.d/user-init/
  #     - mongo_volume:/data_user/db
  #   ports:
  #     - 27100:27017


  # mongo_order:
  #   image: mongo:latest
  #   container_name: db1
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: comp3122
  #     MONGO_INITDB_ROOT_PASSWORD: 23456
  #     MONGO_INITDB_DATABASE: admin
  #   volumes:
  #     - ./order_service/order-init.js:/docker-entrypoint-initdb.d/order-init/
  #     - mongo_volume:/data_order/db
  #   ports:
  #     - 27101:27017
  # order_service:
  #   image: order_service
  #   container_name: s1
  #   build: ./order_service
  #   volumes:
  #     - ./order_service:/app_order
  #   ports:
  #     - 15101:15000

  mongo_restaurant:
    image: mongo:latest
    container_name: db4
    environment:
      MONGO_INITDB_ROOT_USERNAME: comp3122
      MONGO_INITDB_ROOT_PASSWORD: 23456
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./restaurant_service/restaurant-init.js:/docker-entrypoint-initdb.d/restaurant-init/
      - mongo_volume:/data_restaurant/db
    ports:
      - 27104:27017
  restaurant_service:
    image: restaurant_service
    container_name: s4
    build: ./restaurant_service
    volumes:
      - ./restaurant_service/restaurant-init.js:/app_restaurant
    ports:
      - 15104:15000

  # mongo_delivery:
  #   image: mongo:latest
  #   container_name: db5
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: comp3122
  #     MONGO_INITDB_ROOT_PASSWORD: 23456
  #     MONGO_INITDB_DATABASE: admin
  #   volumes:
  #     - mongo_volume:/data_delivery/db
  #   ports:
  #     - 27105:27017
  # delivery_service:
  #   image: delivery_service
  #   container_name: s5
  #   build: ./delivery_service
  #   volumes:
  #     - ./delivery_service:/app_delivery
  #   ports:
  #     - 15105:15000
networks:
  default:
    name: pj_network
volumes:
  mongo_volume:
    name: mongo_vol
