rule_files:
  - alert_rules.yaml
# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: login_service
    scrape_interval: 10s
    static_configs:
      - targets: ['login_service:15000']
  - job_name: restaurant_service
    scrape_interval: 10s
    static_configs:
      - targets: ['restaurant_service:15000']
  - job_name: order_service
    scrape_interval: 10s
    static_configs:
      - targets: ['order_service:15000']