{
 "title": "testing",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Pie chart",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flask_http_request_total{}", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Total HTTP request by status code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 0 },
   "targets": [
    { "expr": "flask_http_request_total{}", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Total successful HTTP request",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total{status=\"200\"}"
    }
   ]
  },
  {
   "title": "Successful insertion and deletion",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "student_added_total{status=\"200\"}"
    },
    {
     "expr": "student_deleted_total{status=\"200\"}"
    },
    {
     "expr": "takes_added_total{status=\"200\"}"
    },
    {
     "expr": "student_deleted_total{status=\"200\"}"
    }
   ]
  },
  {
   "title": "Failed insertion and deletion",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 17, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "student_added_total{status=\"400\"}"
    },
    {
     "expr": "student_deleted_total{status=\"400\"}"
    },
    {
     "expr": "takes_added_total{status=\"400\"}"
    },
    {
     "expr": "takes_deleted_total{status=\"400\"}"
    }
   ]
  },
  {
   "title": "Total failed HTTP request",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total{status=\"400\"}"
    },
    {
     "expr": "flask_http_request_total{status=\"404\"}"
    },
    {
     "expr": "flask_http_request_total{status=\"500\"}"
    }
   ]
  }
 ]
}